version: '2'
services:
  keydb-modjs:
    # TODO: swap back to latest when it is fixed
    # this "test" image is from the keydb team after I encountered some crashes
    # its just an issue with the docker image itself, not with keydb, so we should be ok!
    image: eqalpha/modjs:test
    # image: eqalpha/modjs:keydb-latest

    ports:
      # expose this on a different port to avoid conflict with any locally running redis
      - "6398:6379"
    volumes:
      - ./dist:/scripts
    command: keydb-server /etc/keydb/keydb.conf --loadmodule /usr/lib/keydb/modules/modjs.so /scripts/keydb-startup.js